workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      xcode: latest
    scripts:
      - name: Set up project
        script: |
          # Create scheme if needed
          xcodebuild -list -project BoAnalyst.xcodeproj
      - name: Build iOS app
        script: |
          xcodebuild -project BoAnalyst.xcodeproj \
            -scheme BoAnalyst \
            -sdk iphoneos \
            -configuration Release \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            -archivePath build/BoAnalyst.xcarchive \
            archive
      - name: Create IPA
        script: |
          mkdir -p build/Payload
          cp -r build/BoAnalyst.xcarchive/Products/Applications/BoAnalyst.app build/Payload/
          cd build && zip -r BoAnalyst.ipa Payload
    artifacts:
      - build/*.ipa
    publishing:
      email:
        recipients:
          - your-email@example.com
